// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteService.proto

package com.lzy.neocache.utils.grpc;

public interface ArrayStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ArrayString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string string_array = 1;</code>
   */
  java.util.List<java.lang.String>
      getStringArrayList();
  /**
   * <code>repeated string string_array = 1;</code>
   */
  int getStringArrayCount();
  /**
   * <code>repeated string string_array = 1;</code>
   */
  java.lang.String getStringArray(int index);
  /**
   * <code>repeated string string_array = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringArrayBytes(int index);
}
