// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteService.proto

package com.lzy.neocache.utils.grpc;

/**
 * Protobuf type {@code ArrayString}
 */
public  final class ArrayString extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ArrayString)
    ArrayStringOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ArrayString.newBuilder() to construct.
  private ArrayString(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ArrayString() {
    stringArray_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ArrayString(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              stringArray_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            stringArray_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        stringArray_ = stringArray_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_ArrayString_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_ArrayString_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lzy.neocache.utils.grpc.ArrayString.class, com.lzy.neocache.utils.grpc.ArrayString.Builder.class);
  }

  public static final int STRING_ARRAY_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList stringArray_;
  /**
   * <code>repeated string string_array = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getStringArrayList() {
    return stringArray_;
  }
  /**
   * <code>repeated string string_array = 1;</code>
   */
  public int getStringArrayCount() {
    return stringArray_.size();
  }
  /**
   * <code>repeated string string_array = 1;</code>
   */
  public java.lang.String getStringArray(int index) {
    return stringArray_.get(index);
  }
  /**
   * <code>repeated string string_array = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStringArrayBytes(int index) {
    return stringArray_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < stringArray_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stringArray_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < stringArray_.size(); i++) {
        dataSize += computeStringSizeNoTag(stringArray_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getStringArrayList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lzy.neocache.utils.grpc.ArrayString)) {
      return super.equals(obj);
    }
    com.lzy.neocache.utils.grpc.ArrayString other = (com.lzy.neocache.utils.grpc.ArrayString) obj;

    boolean result = true;
    result = result && getStringArrayList()
        .equals(other.getStringArrayList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStringArrayCount() > 0) {
      hash = (37 * hash) + STRING_ARRAY_FIELD_NUMBER;
      hash = (53 * hash) + getStringArrayList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lzy.neocache.utils.grpc.ArrayString parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lzy.neocache.utils.grpc.ArrayString parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.ArrayString parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lzy.neocache.utils.grpc.ArrayString parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.ArrayString parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lzy.neocache.utils.grpc.ArrayString parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.ArrayString parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lzy.neocache.utils.grpc.ArrayString parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.ArrayString parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lzy.neocache.utils.grpc.ArrayString parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.ArrayString parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lzy.neocache.utils.grpc.ArrayString parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lzy.neocache.utils.grpc.ArrayString prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ArrayString}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ArrayString)
      com.lzy.neocache.utils.grpc.ArrayStringOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_ArrayString_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_ArrayString_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lzy.neocache.utils.grpc.ArrayString.class, com.lzy.neocache.utils.grpc.ArrayString.Builder.class);
    }

    // Construct using com.lzy.neocache.utils.grpc.ArrayString.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      stringArray_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_ArrayString_descriptor;
    }

    public com.lzy.neocache.utils.grpc.ArrayString getDefaultInstanceForType() {
      return com.lzy.neocache.utils.grpc.ArrayString.getDefaultInstance();
    }

    public com.lzy.neocache.utils.grpc.ArrayString build() {
      com.lzy.neocache.utils.grpc.ArrayString result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lzy.neocache.utils.grpc.ArrayString buildPartial() {
      com.lzy.neocache.utils.grpc.ArrayString result = new com.lzy.neocache.utils.grpc.ArrayString(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        stringArray_ = stringArray_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.stringArray_ = stringArray_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lzy.neocache.utils.grpc.ArrayString) {
        return mergeFrom((com.lzy.neocache.utils.grpc.ArrayString)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lzy.neocache.utils.grpc.ArrayString other) {
      if (other == com.lzy.neocache.utils.grpc.ArrayString.getDefaultInstance()) return this;
      if (!other.stringArray_.isEmpty()) {
        if (stringArray_.isEmpty()) {
          stringArray_ = other.stringArray_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureStringArrayIsMutable();
          stringArray_.addAll(other.stringArray_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lzy.neocache.utils.grpc.ArrayString parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lzy.neocache.utils.grpc.ArrayString) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList stringArray_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureStringArrayIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        stringArray_ = new com.google.protobuf.LazyStringArrayList(stringArray_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string string_array = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStringArrayList() {
      return stringArray_.getUnmodifiableView();
    }
    /**
     * <code>repeated string string_array = 1;</code>
     */
    public int getStringArrayCount() {
      return stringArray_.size();
    }
    /**
     * <code>repeated string string_array = 1;</code>
     */
    public java.lang.String getStringArray(int index) {
      return stringArray_.get(index);
    }
    /**
     * <code>repeated string string_array = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringArrayBytes(int index) {
      return stringArray_.getByteString(index);
    }
    /**
     * <code>repeated string string_array = 1;</code>
     */
    public Builder setStringArray(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStringArrayIsMutable();
      stringArray_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string string_array = 1;</code>
     */
    public Builder addStringArray(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStringArrayIsMutable();
      stringArray_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string string_array = 1;</code>
     */
    public Builder addAllStringArray(
        java.lang.Iterable<java.lang.String> values) {
      ensureStringArrayIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, stringArray_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string string_array = 1;</code>
     */
    public Builder clearStringArray() {
      stringArray_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string string_array = 1;</code>
     */
    public Builder addStringArrayBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureStringArrayIsMutable();
      stringArray_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ArrayString)
  }

  // @@protoc_insertion_point(class_scope:ArrayString)
  private static final com.lzy.neocache.utils.grpc.ArrayString DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lzy.neocache.utils.grpc.ArrayString();
  }

  public static com.lzy.neocache.utils.grpc.ArrayString getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ArrayString>
      PARSER = new com.google.protobuf.AbstractParser<ArrayString>() {
    public ArrayString parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ArrayString(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ArrayString> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ArrayString> getParserForType() {
    return PARSER;
  }

  public com.lzy.neocache.utils.grpc.ArrayString getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

