// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteService.proto

package com.lzy.neocache.utils.grpc;

public interface DataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Data)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string string = 1;</code>
   */
  java.lang.String getString();
  /**
   * <code>string string = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringBytes();

  /**
   * <code>.ArrayString arrayString = 2;</code>
   */
  boolean hasArrayString();
  /**
   * <code>.ArrayString arrayString = 2;</code>
   */
  com.lzy.neocache.utils.grpc.ArrayString getArrayString();
  /**
   * <code>.ArrayString arrayString = 2;</code>
   */
  com.lzy.neocache.utils.grpc.ArrayStringOrBuilder getArrayStringOrBuilder();

  public com.lzy.neocache.utils.grpc.Data.DataValueCase getDataValueCase();
}
