// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteService.proto

package com.lzy.neocache.utils.grpc;

/**
 * Protobuf type {@code Data}
 */
public  final class Data extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Data)
    DataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Data.newBuilder() to construct.
  private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Data() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Data(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            dataValueCase_ = 1;
            dataValue_ = s;
            break;
          }
          case 18: {
            com.lzy.neocache.utils.grpc.ArrayString.Builder subBuilder = null;
            if (dataValueCase_ == 2) {
              subBuilder = ((com.lzy.neocache.utils.grpc.ArrayString) dataValue_).toBuilder();
            }
            dataValue_ =
                input.readMessage(com.lzy.neocache.utils.grpc.ArrayString.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.lzy.neocache.utils.grpc.ArrayString) dataValue_);
              dataValue_ = subBuilder.buildPartial();
            }
            dataValueCase_ = 2;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_Data_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_Data_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lzy.neocache.utils.grpc.Data.class, com.lzy.neocache.utils.grpc.Data.Builder.class);
  }

  private int dataValueCase_ = 0;
  private java.lang.Object dataValue_;
  public enum DataValueCase
      implements com.google.protobuf.Internal.EnumLite {
    STRING(1),
    ARRAYSTRING(2),
    DATAVALUE_NOT_SET(0);
    private final int value;
    private DataValueCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataValueCase forNumber(int value) {
      switch (value) {
        case 1: return STRING;
        case 2: return ARRAYSTRING;
        case 0: return DATAVALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataValueCase
  getDataValueCase() {
    return DataValueCase.forNumber(
        dataValueCase_);
  }

  public static final int STRING_FIELD_NUMBER = 1;
  /**
   * <code>string string = 1;</code>
   */
  public java.lang.String getString() {
    java.lang.Object ref = "";
    if (dataValueCase_ == 1) {
      ref = dataValue_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (dataValueCase_ == 1) {
        dataValue_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string string = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStringBytes() {
    java.lang.Object ref = "";
    if (dataValueCase_ == 1) {
      ref = dataValue_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (dataValueCase_ == 1) {
        dataValue_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARRAYSTRING_FIELD_NUMBER = 2;
  /**
   * <code>.ArrayString arrayString = 2;</code>
   */
  public boolean hasArrayString() {
    return dataValueCase_ == 2;
  }
  /**
   * <code>.ArrayString arrayString = 2;</code>
   */
  public com.lzy.neocache.utils.grpc.ArrayString getArrayString() {
    if (dataValueCase_ == 2) {
       return (com.lzy.neocache.utils.grpc.ArrayString) dataValue_;
    }
    return com.lzy.neocache.utils.grpc.ArrayString.getDefaultInstance();
  }
  /**
   * <code>.ArrayString arrayString = 2;</code>
   */
  public com.lzy.neocache.utils.grpc.ArrayStringOrBuilder getArrayStringOrBuilder() {
    if (dataValueCase_ == 2) {
       return (com.lzy.neocache.utils.grpc.ArrayString) dataValue_;
    }
    return com.lzy.neocache.utils.grpc.ArrayString.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataValueCase_ == 1) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataValue_);
    }
    if (dataValueCase_ == 2) {
      output.writeMessage(2, (com.lzy.neocache.utils.grpc.ArrayString) dataValue_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dataValueCase_ == 1) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataValue_);
    }
    if (dataValueCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.lzy.neocache.utils.grpc.ArrayString) dataValue_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lzy.neocache.utils.grpc.Data)) {
      return super.equals(obj);
    }
    com.lzy.neocache.utils.grpc.Data other = (com.lzy.neocache.utils.grpc.Data) obj;

    boolean result = true;
    result = result && getDataValueCase().equals(
        other.getDataValueCase());
    if (!result) return false;
    switch (dataValueCase_) {
      case 1:
        result = result && getString()
            .equals(other.getString());
        break;
      case 2:
        result = result && getArrayString()
            .equals(other.getArrayString());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (dataValueCase_) {
      case 1:
        hash = (37 * hash) + STRING_FIELD_NUMBER;
        hash = (53 * hash) + getString().hashCode();
        break;
      case 2:
        hash = (37 * hash) + ARRAYSTRING_FIELD_NUMBER;
        hash = (53 * hash) + getArrayString().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lzy.neocache.utils.grpc.Data parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lzy.neocache.utils.grpc.Data parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.Data parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lzy.neocache.utils.grpc.Data parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.Data parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lzy.neocache.utils.grpc.Data parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.Data parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lzy.neocache.utils.grpc.Data parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.Data parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lzy.neocache.utils.grpc.Data parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.Data parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lzy.neocache.utils.grpc.Data parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lzy.neocache.utils.grpc.Data prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Data}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Data)
      com.lzy.neocache.utils.grpc.DataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lzy.neocache.utils.grpc.Data.class, com.lzy.neocache.utils.grpc.Data.Builder.class);
    }

    // Construct using com.lzy.neocache.utils.grpc.Data.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      dataValueCase_ = 0;
      dataValue_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_Data_descriptor;
    }

    public com.lzy.neocache.utils.grpc.Data getDefaultInstanceForType() {
      return com.lzy.neocache.utils.grpc.Data.getDefaultInstance();
    }

    public com.lzy.neocache.utils.grpc.Data build() {
      com.lzy.neocache.utils.grpc.Data result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lzy.neocache.utils.grpc.Data buildPartial() {
      com.lzy.neocache.utils.grpc.Data result = new com.lzy.neocache.utils.grpc.Data(this);
      if (dataValueCase_ == 1) {
        result.dataValue_ = dataValue_;
      }
      if (dataValueCase_ == 2) {
        if (arrayStringBuilder_ == null) {
          result.dataValue_ = dataValue_;
        } else {
          result.dataValue_ = arrayStringBuilder_.build();
        }
      }
      result.dataValueCase_ = dataValueCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lzy.neocache.utils.grpc.Data) {
        return mergeFrom((com.lzy.neocache.utils.grpc.Data)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lzy.neocache.utils.grpc.Data other) {
      if (other == com.lzy.neocache.utils.grpc.Data.getDefaultInstance()) return this;
      switch (other.getDataValueCase()) {
        case STRING: {
          dataValueCase_ = 1;
          dataValue_ = other.dataValue_;
          onChanged();
          break;
        }
        case ARRAYSTRING: {
          mergeArrayString(other.getArrayString());
          break;
        }
        case DATAVALUE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lzy.neocache.utils.grpc.Data parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lzy.neocache.utils.grpc.Data) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataValueCase_ = 0;
    private java.lang.Object dataValue_;
    public DataValueCase
        getDataValueCase() {
      return DataValueCase.forNumber(
          dataValueCase_);
    }

    public Builder clearDataValue() {
      dataValueCase_ = 0;
      dataValue_ = null;
      onChanged();
      return this;
    }


    /**
     * <code>string string = 1;</code>
     */
    public java.lang.String getString() {
      java.lang.Object ref = "";
      if (dataValueCase_ == 1) {
        ref = dataValue_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (dataValueCase_ == 1) {
          dataValue_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string string = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = "";
      if (dataValueCase_ == 1) {
        ref = dataValue_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (dataValueCase_ == 1) {
          dataValue_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string string = 1;</code>
     */
    public Builder setString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  dataValueCase_ = 1;
      dataValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string string = 1;</code>
     */
    public Builder clearString() {
      if (dataValueCase_ == 1) {
        dataValueCase_ = 0;
        dataValue_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string string = 1;</code>
     */
    public Builder setStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      dataValueCase_ = 1;
      dataValue_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.lzy.neocache.utils.grpc.ArrayString, com.lzy.neocache.utils.grpc.ArrayString.Builder, com.lzy.neocache.utils.grpc.ArrayStringOrBuilder> arrayStringBuilder_;
    /**
     * <code>.ArrayString arrayString = 2;</code>
     */
    public boolean hasArrayString() {
      return dataValueCase_ == 2;
    }
    /**
     * <code>.ArrayString arrayString = 2;</code>
     */
    public com.lzy.neocache.utils.grpc.ArrayString getArrayString() {
      if (arrayStringBuilder_ == null) {
        if (dataValueCase_ == 2) {
          return (com.lzy.neocache.utils.grpc.ArrayString) dataValue_;
        }
        return com.lzy.neocache.utils.grpc.ArrayString.getDefaultInstance();
      } else {
        if (dataValueCase_ == 2) {
          return arrayStringBuilder_.getMessage();
        }
        return com.lzy.neocache.utils.grpc.ArrayString.getDefaultInstance();
      }
    }
    /**
     * <code>.ArrayString arrayString = 2;</code>
     */
    public Builder setArrayString(com.lzy.neocache.utils.grpc.ArrayString value) {
      if (arrayStringBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataValue_ = value;
        onChanged();
      } else {
        arrayStringBuilder_.setMessage(value);
      }
      dataValueCase_ = 2;
      return this;
    }
    /**
     * <code>.ArrayString arrayString = 2;</code>
     */
    public Builder setArrayString(
        com.lzy.neocache.utils.grpc.ArrayString.Builder builderForValue) {
      if (arrayStringBuilder_ == null) {
        dataValue_ = builderForValue.build();
        onChanged();
      } else {
        arrayStringBuilder_.setMessage(builderForValue.build());
      }
      dataValueCase_ = 2;
      return this;
    }
    /**
     * <code>.ArrayString arrayString = 2;</code>
     */
    public Builder mergeArrayString(com.lzy.neocache.utils.grpc.ArrayString value) {
      if (arrayStringBuilder_ == null) {
        if (dataValueCase_ == 2 &&
            dataValue_ != com.lzy.neocache.utils.grpc.ArrayString.getDefaultInstance()) {
          dataValue_ = com.lzy.neocache.utils.grpc.ArrayString.newBuilder((com.lzy.neocache.utils.grpc.ArrayString) dataValue_)
              .mergeFrom(value).buildPartial();
        } else {
          dataValue_ = value;
        }
        onChanged();
      } else {
        if (dataValueCase_ == 2) {
          arrayStringBuilder_.mergeFrom(value);
        }
        arrayStringBuilder_.setMessage(value);
      }
      dataValueCase_ = 2;
      return this;
    }
    /**
     * <code>.ArrayString arrayString = 2;</code>
     */
    public Builder clearArrayString() {
      if (arrayStringBuilder_ == null) {
        if (dataValueCase_ == 2) {
          dataValueCase_ = 0;
          dataValue_ = null;
          onChanged();
        }
      } else {
        if (dataValueCase_ == 2) {
          dataValueCase_ = 0;
          dataValue_ = null;
        }
        arrayStringBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ArrayString arrayString = 2;</code>
     */
    public com.lzy.neocache.utils.grpc.ArrayString.Builder getArrayStringBuilder() {
      return getArrayStringFieldBuilder().getBuilder();
    }
    /**
     * <code>.ArrayString arrayString = 2;</code>
     */
    public com.lzy.neocache.utils.grpc.ArrayStringOrBuilder getArrayStringOrBuilder() {
      if ((dataValueCase_ == 2) && (arrayStringBuilder_ != null)) {
        return arrayStringBuilder_.getMessageOrBuilder();
      } else {
        if (dataValueCase_ == 2) {
          return (com.lzy.neocache.utils.grpc.ArrayString) dataValue_;
        }
        return com.lzy.neocache.utils.grpc.ArrayString.getDefaultInstance();
      }
    }
    /**
     * <code>.ArrayString arrayString = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lzy.neocache.utils.grpc.ArrayString, com.lzy.neocache.utils.grpc.ArrayString.Builder, com.lzy.neocache.utils.grpc.ArrayStringOrBuilder> 
        getArrayStringFieldBuilder() {
      if (arrayStringBuilder_ == null) {
        if (!(dataValueCase_ == 2)) {
          dataValue_ = com.lzy.neocache.utils.grpc.ArrayString.getDefaultInstance();
        }
        arrayStringBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lzy.neocache.utils.grpc.ArrayString, com.lzy.neocache.utils.grpc.ArrayString.Builder, com.lzy.neocache.utils.grpc.ArrayStringOrBuilder>(
                (com.lzy.neocache.utils.grpc.ArrayString) dataValue_,
                getParentForChildren(),
                isClean());
        dataValue_ = null;
      }
      dataValueCase_ = 2;
      onChanged();;
      return arrayStringBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Data)
  }

  // @@protoc_insertion_point(class_scope:Data)
  private static final com.lzy.neocache.utils.grpc.Data DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lzy.neocache.utils.grpc.Data();
  }

  public static com.lzy.neocache.utils.grpc.Data getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Data>
      PARSER = new com.google.protobuf.AbstractParser<Data>() {
    public Data parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Data(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Data> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Data> getParserForType() {
    return PARSER;
  }

  public com.lzy.neocache.utils.grpc.Data getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

