// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteService.proto

package com.lzy.neocache.utils.grpc;

public interface RemoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RemoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.Data value = 2;</code>
   */
  boolean hasValue();
  /**
   * <code>.Data value = 2;</code>
   */
  com.lzy.neocache.utils.grpc.Data getValue();
  /**
   * <code>.Data value = 2;</code>
   */
  com.lzy.neocache.utils.grpc.DataOrBuilder getValueOrBuilder();
}
