// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteService.proto

package com.lzy.neocache.utils.grpc;

public interface RemoteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RemoteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Data value = 1;</code>
   */
  boolean hasValue();
  /**
   * <code>.Data value = 1;</code>
   */
  com.lzy.neocache.utils.grpc.Data getValue();
  /**
   * <code>.Data value = 1;</code>
   */
  com.lzy.neocache.utils.grpc.DataOrBuilder getValueOrBuilder();
}
