// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteService.proto

package com.lzy.neocache.utils.grpc;

public final class RemoteServiceOuterClass {
  private RemoteServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RemoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RemoteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Data_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ArrayString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ArrayString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023RemoteService.proto\"2\n\rRemoteRequest\022\013" +
      "\n\003key\030\001 \001(\t\022\024\n\005value\030\002 \001(\0132\005.Data\"&\n\016Rem" +
      "oteResponse\022\024\n\005value\030\001 \001(\0132\005.Data\"J\n\004Dat" +
      "a\022\020\n\006string\030\001 \001(\tH\000\022#\n\013arrayString\030\002 \001(\013" +
      "2\014.ArrayStringH\000B\013\n\tdataValue\"#\n\013ArraySt" +
      "ring\022\024\n\014string_array\030\001 \003(\t2\212\001\n\rRemoteSer" +
      "vice\022&\n\003Get\022\016.RemoteRequest\032\017.RemoteResp" +
      "onse\022&\n\003Add\022\016.RemoteRequest\032\017.RemoteResp" +
      "onse\022)\n\006Delete\022\016.RemoteRequest\032\017.RemoteR" +
      "esponseB\037\n\033com.lzy.neocache.utils.grpcP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RemoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RemoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RemoteRequest_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_RemoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RemoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RemoteResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_Data_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Data_descriptor,
        new java.lang.String[] { "String", "ArrayString", "DataValue", });
    internal_static_ArrayString_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ArrayString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ArrayString_descriptor,
        new java.lang.String[] { "StringArray", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
