// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteService.proto

package com.lzy.neocache.utils.grpc;

/**
 * Protobuf type {@code RemoteResponse}
 */
public  final class RemoteResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RemoteResponse)
    RemoteResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RemoteResponse.newBuilder() to construct.
  private RemoteResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RemoteResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RemoteResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.lzy.neocache.utils.grpc.Data.Builder subBuilder = null;
            if (value_ != null) {
              subBuilder = value_.toBuilder();
            }
            value_ = input.readMessage(com.lzy.neocache.utils.grpc.Data.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(value_);
              value_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_RemoteResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_RemoteResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lzy.neocache.utils.grpc.RemoteResponse.class, com.lzy.neocache.utils.grpc.RemoteResponse.Builder.class);
  }

  public static final int VALUE_FIELD_NUMBER = 1;
  private com.lzy.neocache.utils.grpc.Data value_;
  /**
   * <code>.Data value = 1;</code>
   */
  public boolean hasValue() {
    return value_ != null;
  }
  /**
   * <code>.Data value = 1;</code>
   */
  public com.lzy.neocache.utils.grpc.Data getValue() {
    return value_ == null ? com.lzy.neocache.utils.grpc.Data.getDefaultInstance() : value_;
  }
  /**
   * <code>.Data value = 1;</code>
   */
  public com.lzy.neocache.utils.grpc.DataOrBuilder getValueOrBuilder() {
    return getValue();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (value_ != null) {
      output.writeMessage(1, getValue());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (value_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getValue());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lzy.neocache.utils.grpc.RemoteResponse)) {
      return super.equals(obj);
    }
    com.lzy.neocache.utils.grpc.RemoteResponse other = (com.lzy.neocache.utils.grpc.RemoteResponse) obj;

    boolean result = true;
    result = result && (hasValue() == other.hasValue());
    if (hasValue()) {
      result = result && getValue()
          .equals(other.getValue());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lzy.neocache.utils.grpc.RemoteResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lzy.neocache.utils.grpc.RemoteResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.RemoteResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lzy.neocache.utils.grpc.RemoteResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.RemoteResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lzy.neocache.utils.grpc.RemoteResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.RemoteResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lzy.neocache.utils.grpc.RemoteResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.RemoteResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lzy.neocache.utils.grpc.RemoteResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lzy.neocache.utils.grpc.RemoteResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lzy.neocache.utils.grpc.RemoteResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lzy.neocache.utils.grpc.RemoteResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RemoteResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RemoteResponse)
      com.lzy.neocache.utils.grpc.RemoteResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_RemoteResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_RemoteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lzy.neocache.utils.grpc.RemoteResponse.class, com.lzy.neocache.utils.grpc.RemoteResponse.Builder.class);
    }

    // Construct using com.lzy.neocache.utils.grpc.RemoteResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (valueBuilder_ == null) {
        value_ = null;
      } else {
        value_ = null;
        valueBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lzy.neocache.utils.grpc.RemoteServiceOuterClass.internal_static_RemoteResponse_descriptor;
    }

    public com.lzy.neocache.utils.grpc.RemoteResponse getDefaultInstanceForType() {
      return com.lzy.neocache.utils.grpc.RemoteResponse.getDefaultInstance();
    }

    public com.lzy.neocache.utils.grpc.RemoteResponse build() {
      com.lzy.neocache.utils.grpc.RemoteResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lzy.neocache.utils.grpc.RemoteResponse buildPartial() {
      com.lzy.neocache.utils.grpc.RemoteResponse result = new com.lzy.neocache.utils.grpc.RemoteResponse(this);
      if (valueBuilder_ == null) {
        result.value_ = value_;
      } else {
        result.value_ = valueBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lzy.neocache.utils.grpc.RemoteResponse) {
        return mergeFrom((com.lzy.neocache.utils.grpc.RemoteResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lzy.neocache.utils.grpc.RemoteResponse other) {
      if (other == com.lzy.neocache.utils.grpc.RemoteResponse.getDefaultInstance()) return this;
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lzy.neocache.utils.grpc.RemoteResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lzy.neocache.utils.grpc.RemoteResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.lzy.neocache.utils.grpc.Data value_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lzy.neocache.utils.grpc.Data, com.lzy.neocache.utils.grpc.Data.Builder, com.lzy.neocache.utils.grpc.DataOrBuilder> valueBuilder_;
    /**
     * <code>.Data value = 1;</code>
     */
    public boolean hasValue() {
      return valueBuilder_ != null || value_ != null;
    }
    /**
     * <code>.Data value = 1;</code>
     */
    public com.lzy.neocache.utils.grpc.Data getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? com.lzy.neocache.utils.grpc.Data.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <code>.Data value = 1;</code>
     */
    public Builder setValue(com.lzy.neocache.utils.grpc.Data value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        valueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Data value = 1;</code>
     */
    public Builder setValue(
        com.lzy.neocache.utils.grpc.Data.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Data value = 1;</code>
     */
    public Builder mergeValue(com.lzy.neocache.utils.grpc.Data value) {
      if (valueBuilder_ == null) {
        if (value_ != null) {
          value_ =
            com.lzy.neocache.utils.grpc.Data.newBuilder(value_).mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        valueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Data value = 1;</code>
     */
    public Builder clearValue() {
      if (valueBuilder_ == null) {
        value_ = null;
        onChanged();
      } else {
        value_ = null;
        valueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Data value = 1;</code>
     */
    public com.lzy.neocache.utils.grpc.Data.Builder getValueBuilder() {
      
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.Data value = 1;</code>
     */
    public com.lzy.neocache.utils.grpc.DataOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            com.lzy.neocache.utils.grpc.Data.getDefaultInstance() : value_;
      }
    }
    /**
     * <code>.Data value = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lzy.neocache.utils.grpc.Data, com.lzy.neocache.utils.grpc.Data.Builder, com.lzy.neocache.utils.grpc.DataOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lzy.neocache.utils.grpc.Data, com.lzy.neocache.utils.grpc.Data.Builder, com.lzy.neocache.utils.grpc.DataOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RemoteResponse)
  }

  // @@protoc_insertion_point(class_scope:RemoteResponse)
  private static final com.lzy.neocache.utils.grpc.RemoteResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lzy.neocache.utils.grpc.RemoteResponse();
  }

  public static com.lzy.neocache.utils.grpc.RemoteResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RemoteResponse>
      PARSER = new com.google.protobuf.AbstractParser<RemoteResponse>() {
    public RemoteResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RemoteResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RemoteResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RemoteResponse> getParserForType() {
    return PARSER;
  }

  public com.lzy.neocache.utils.grpc.RemoteResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

